export const ADMIN_TOURNAMENTS_REQUEST = 'ADMIN_TOURNAMENTS_REQUEST';
export const ADMIN_TOURNAMENTS_SUCCESS = 'ADMIN_TOURNAMENTS_SUCCESS';
export const ADMIN_TOURNAMENTS_FAIL = 'ADMIN_TOURNAMENTS_FAIL';

export const ALL_TOURNAMENTS_REQUEST = 'ALL_TOURNAMENTS_REQUEST';
export const ALL_TOURNAMENTS_SUCCESS = 'ALL_TOURNAMENTS_SUCCESS';
export const ALL_TOURNAMENTS_FAIL = 'ALL_TOURNAMENTS_FAIL';

export const NEW_TOURNAMENT_REQUEST = 'NEW_TOURNAMENT_REQUEST';
export const NEW_TOURNAMENT_SUCCESS = 'NEW_TOURNAMENT_SUCCESS';
export const NEW_TOURNAMENT_RESET = 'NEW_TOURNAMENT_RESET';
export const NEW_TOURNAMENT_FAIL = 'NEW_TOURNAMENT_FAIL';

export const DELETE_TOURNAMENT_REQUEST = 'DELETE_TOURNAMENT_REQUEST';
export const DELETE_TOURNAMENT_SUCCESS = 'DELETE_TOURNAMENT_SUCCESS';
export const DELETE_TOURNAMENT_RESET = 'DELETE_TOURNAMENT_RESET';
export const DELETE_TOURNAMENT_FAIL = 'DELETE_TOURNAMENT_FAIL';

export const UPDATE_TOURNAMENT_REQUEST = 'UPDATE_TOURNAMENT_REQUEST';
export const UPDATE_TOURNAMENT_SUCCESS = 'UPDATE_TOURNAMENT_SUCCESS';
export const UPDATE_TOURNAMENT_RESET = 'UPDATE_TOURNAMENT_RESET';
export const UPDATE_TOURNAMENT_FAIL = 'UPDATE_TOURNAMENT_FAIL';

export const TOURNAMENT_DETAILS_REQUEST = 'TOURNAMENT_DETAILS_REQUEST';
export const TOURNAMENT_DETAILS_SUCCESS = 'TOURNAMENT_DETAILS_SUCCESS';
export const TOURNAMENT_DETAILS_FAIL = 'TOURNAMENT_DETAILS_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
